# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Microprocess2\Lab1\Design01.cydsn\Design01.cyprj
# Date: Wed, 12 Feb 2025 15:28:00 GMT
#set_units -time ns
create_clock -name {Clock(FFB)} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ff_div_8}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 24001 48001} [list]


# Component constraints for D:\Microprocess2\Lab1\Design01.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Microprocess2\Lab1\Design01.cydsn\Design01.cyprj
# Date: Wed, 12 Feb 2025 15:27:58 GMT
