/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* NO_ALERT */
#define NO_ALERT_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define NO_ALERT_0_INBUF_ENABLED 0u
#define NO_ALERT_0_INIT_DRIVESTATE 0u
#define NO_ALERT_0_INIT_MUXSEL 0u
#define NO_ALERT_0_INPUT_SYNC 2u
#define NO_ALERT_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define NO_ALERT_0_NUM 1u
#define NO_ALERT_0_PORT GPIO_PRT11
#define NO_ALERT_0_SLEWRATE CY_GPIO_SLEW_FAST
#define NO_ALERT_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define NO_ALERT_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define NO_ALERT_INBUF_ENABLED 0u
#define NO_ALERT_INIT_DRIVESTATE 0u
#define NO_ALERT_INIT_MUXSEL 0u
#define NO_ALERT_INPUT_SYNC 2u
#define NO_ALERT_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define NO_ALERT_NUM 1u
#define NO_ALERT_PORT GPIO_PRT11
#define NO_ALERT_SLEWRATE CY_GPIO_SLEW_FAST
#define NO_ALERT_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Alert_LED */
#define Alert_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_0_INBUF_ENABLED 0u
#define Alert_LED_0_INIT_DRIVESTATE 0u
#define Alert_LED_0_INIT_MUXSEL 0u
#define Alert_LED_0_INPUT_SYNC 2u
#define Alert_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_0_NUM 7u
#define Alert_LED_0_PORT GPIO_PRT13
#define Alert_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Alert_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_LED_INBUF_ENABLED 0u
#define Alert_LED_INIT_DRIVESTATE 0u
#define Alert_LED_INIT_MUXSEL 0u
#define Alert_LED_INPUT_SYNC 2u
#define Alert_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_LED_NUM 7u
#define Alert_LED_PORT GPIO_PRT13
#define Alert_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Alert_Midl */
#define Alert_Midl_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_Midl_0_INBUF_ENABLED 0u
#define Alert_Midl_0_INIT_DRIVESTATE 0u
#define Alert_Midl_0_INIT_MUXSEL 0u
#define Alert_Midl_0_INPUT_SYNC 2u
#define Alert_Midl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_Midl_0_NUM 5u
#define Alert_Midl_0_PORT GPIO_PRT1
#define Alert_Midl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_Midl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Alert_Midl_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Alert_Midl_INBUF_ENABLED 0u
#define Alert_Midl_INIT_DRIVESTATE 0u
#define Alert_Midl_INIT_MUXSEL 0u
#define Alert_Midl_INPUT_SYNC 2u
#define Alert_Midl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Alert_Midl_NUM 5u
#define Alert_Midl_PORT GPIO_PRT1
#define Alert_Midl_SLEWRATE CY_GPIO_SLEW_FAST
#define Alert_Midl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Disconnect_LED */
#define Disconnect_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_0_INBUF_ENABLED 0u
#define Disconnect_LED_0_INIT_DRIVESTATE 0u
#define Disconnect_LED_0_INIT_MUXSEL 0u
#define Disconnect_LED_0_INPUT_SYNC 2u
#define Disconnect_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_0_NUM 3u
#define Disconnect_LED_0_PORT GPIO_PRT0
#define Disconnect_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Disconnect_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Disconnect_LED_INBUF_ENABLED 0u
#define Disconnect_LED_INIT_DRIVESTATE 0u
#define Disconnect_LED_INIT_MUXSEL 0u
#define Disconnect_LED_INPUT_SYNC 2u
#define Disconnect_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Disconnect_LED_NUM 3u
#define Disconnect_LED_PORT GPIO_PRT0
#define Disconnect_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Disconnect_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Advertising_LED */
#define Advertising_LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_0_INBUF_ENABLED 0u
#define Advertising_LED_0_INIT_DRIVESTATE 0u
#define Advertising_LED_0_INIT_MUXSEL 0u
#define Advertising_LED_0_INPUT_SYNC 2u
#define Advertising_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_0_NUM 1u
#define Advertising_LED_0_PORT GPIO_PRT1
#define Advertising_LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Advertising_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Advertising_LED_INBUF_ENABLED 0u
#define Advertising_LED_INIT_DRIVESTATE 0u
#define Advertising_LED_INIT_MUXSEL 0u
#define Advertising_LED_INPUT_SYNC 2u
#define Advertising_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Advertising_LED_NUM 1u
#define Advertising_LED_PORT GPIO_PRT1
#define Advertising_LED_SLEWRATE CY_GPIO_SLEW_FAST
#define Advertising_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
